# datasource property
spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/shipping_company_application
spring.datasource.username=root
spring.datasource.password=Asteway17*

spring.mvc.pathmatch.matching-strategy=ant_path_matcher
kafka.topicName = "shippingEmailTopic"

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username="shippingapplicationtest@gmail.com"
spring.mail.password="avtxkpnqyklqsvqj"
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
